title: Ctlos Shop
email: creio@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
  Интернет магазин принтов Ctlos, закажи хорошую вешь с самым крутым логотипом
baseurl: "/shop" # the subpath of your site, e.g. /blog
url: "https://ctlos.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# lang:
# twitter_username:
github_username: ctlos

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  - products
